name: aws-lambda-starter
component: aws-lambda
org: serverlessinc
description: Deploys an AWS Lambda function
keywords: aws, serverless, faas, lambda
repo: https://github.com/serverless-components/aws-lambda
license: MIT

inputs:
  src: ./src
  handler: handler.handler
